apiVersion: v1
kind: Service
metadata:
  name: homebaker-frontend
  namespace: homebaker
spec:
  selector:
    app: homebaker-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
