apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - baker-service.yaml
  - baker-service-service.yaml
  - frontend.yaml
  - frontend-service.yaml
  - pod-monitoring.yaml
