apiVersion: v1
kind: Service
metadata:
  name: homebaker-frontend
  namespace: homebaker
  labels:
    app: homebaker-frontend
    {{- include "homebaker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: homebaker-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
